name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  uptime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.39.0
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
